# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 643ebdd637c524d7cf512a13be499b6a1b6b938d1b1385df12b297eb4066db0c989a4e463c0f95539b472b20f9a9c280a566c91789299ae2f7412323833d3ad0

test:
  secret_key_base: 967df84b4937f8b8fb677dd691846dac7db5ed92c4e1cdf3e4ad6497cf5196fc3b96d0e6e6a77827c943b30b9fc90fd8b13adca4425153d7ace6c0aa9ba83742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
